# Server port
server.port=8080

# Mpesa Daraja configuration
mpesa.grantType=client_credentials
mpesa.oauthEndpoint=https://sandbox.safaricom.co.ke/oauth/v1/generate
mpesa.baseUrl=
mpesa.consumerKey=
mpesa.consumerSecret=
mpesa.passkey=
mpesa.callbackUrl=https://79b20c457596.ngrok-free.app
mpesa.environment=sandbox
mpesa.businessShortCzode=174379
