# Mpesa Credentials
mpesa.consumer-key=...
mpesa.consumer-secret=...
mpesa.business-short-code=174379
mpesa.passkey=...
# Paste your full ngrok URL, including the endpoint path
mpesa.callback-url=https://random-string-of-words.ngrok-free.app/api/payments/callback
mpesa.environment=sandbox